Dialect support for stix-shifter connector
opencybersecurityalliance/kestrel-lang pull request #279
Opened 2023-01-23 23:25 UTC by cmadam

This addresses issue https://github.com/opencybersecurityalliance/kestrel-lang/issues/270  

We have established that the capability to specify a dialect in a STIX shifter profiler is already there, and enhanced a profile example in the documentation to show how to add a dialect to that profile.

2023-01-23 23:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/opencybersecurityalliance/kestrel-lang?pullRequest=279) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/opencybersecurityalliance/kestrel-lang?pullRequest=279) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/opencybersecurityalliance/kestrel-lang?pullRequest=279) it.</sub>

2023-01-24 18:02 UTC, subbyte approved these changes

2023-01-24 18:05 UTC, subbyte requested changes

2023-01-24 18:05 UTC, subbyte commented on src/kestrel_datasource_stixshifter/interface.py
> +                        dialects: # for more info about dialects, see https://github.com/opensecurityalliance/stix-shifter/blob/develop/OVERVIEW.md
A typo in the link?

2023-01-24 18:14 UTC, cmadam commented on src/kestrel_datasource_stixshifter/interface.py
> +                        dialects: # for more info about dialects, see https://github.com/opensecurityalliance/stix-shifter/blob/develop/OVERVIEW.md
Sorry, I corrected the link now.

2023-01-25 22:46 UTC, subbyte approved these changes

2023-01-25 22:46 UTC, merged