Removed keyword argument "force" from logging.basicConfig.
opencybersecurityalliance/kestrel-lang pull request #98
Opened 2021-08-11 09:32 UTC by kinzhong

This pull request fixes https://github.com/opencybersecurityalliance/kestrel-lang/issues/97.

2021-08-11 09:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/opencybersecurityalliance/kestrel-lang?pullRequest=98) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/opencybersecurityalliance/kestrel-lang?pullRequest=98) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/opencybersecurityalliance/kestrel-lang?pullRequest=98) it.</sub>

2021-08-12 14:27 UTC, subbyte reviewed
Thanks for the PR, @kinzhong !

We need to do a little more than just removing the parameter. The function `logging_setup()` is called twice in `__main__.py` before and after the session starts with logging file created. The expected behavior is to output log to stdout/stderr before the creation of the logging file and then into the logging file (may plus the stdout/stderr depending on `verbose_mode`). However, the root logger created by `basicConfig` will not be completely replaced by the new one unless `force` is used. That is why I say we need to manually remove the root loggers such as stderr if we do not use `force=true` --- basically implement the functionality of `force` for `logging` (when the earlier versions does not have the parameter).

2021-08-16 10:09 UTC, kinzhong commented
I see. I have added that functionality. Please take a look @subbyte. Also, I apologize in advance if there are mistakes. It's my first time dealing with Python logging!

2021-08-18 16:46 UTC, subbyte requested changes
Great! The last change needed is to black the code. Just `pip install black` and `black src` which should take care of the file you edited.

2021-08-23 17:30 UTC, subbyte approved these changes

2021-08-23 17:38 UTC, merged